# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QLabel,
    QLineEdit, QMainWindow, QMenu, QMenuBar,
    QPlainTextEdit, QPushButton, QSizePolicy, QStatusBar,
    QTabWidget, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(726, 674)
        self.actionOpenExcel = QAction(MainWindow)
        self.actionOpenExcel.setObjectName(u"actionOpenExcel")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.filePathLabel = QLabel(self.tab)
        self.filePathLabel.setObjectName(u"filePathLabel")
        self.filePathLabel.setGeometry(QRect(180, 20, 491, 40))
        self.filePathLabel.setMinimumSize(QSize(300, 40))
        self.filePathLabel.setMaximumSize(QSize(500, 40))
        font = QFont()
        font.setFamilies([u"\ub9d1\uc740 \uace0\ub515"])
        font.setPointSize(9)
        font.setBold(False)
        self.filePathLabel.setFont(font)
        self.filePathLabel.setFrameShape(QFrame.Shape.Panel)
        self.filePathLabel.setFrameShadow(QFrame.Shadow.Sunken)
        self.filePathLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.filePathLabel.setMargin(5)
        self.plainTextEdit = QPlainTextEdit(self.tab)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(30, 80, 641, 401))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setFrameShape(QFrame.Shape.StyledPanel)
        self.plainTextEdit.setFrameShadow(QFrame.Shadow.Plain)
        self.label_logo = QLabel(self.tab)
        self.label_logo.setObjectName(u"label_logo")
        self.label_logo.setGeometry(QRect(20, 20, 151, 41))
        font1 = QFont()
        font1.setPointSize(9)
        font1.setBold(False)
        self.label_logo.setFont(font1)
        self.label_logo.setFrameShape(QFrame.Shape.StyledPanel)
        self.label_logo.setFrameShadow(QFrame.Shadow.Plain)
        self.label_logo.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.label_invoice = QLabel(self.tab_3)
        self.label_invoice.setObjectName(u"label_invoice")
        self.label_invoice.setGeometry(QRect(150, 30, 351, 40))
        self.label_invoice.setFrameShape(QFrame.Shape.Panel)
        self.label_invoice.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_invoice.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.pushButton_load_invoice = QPushButton(self.tab_3)
        self.pushButton_load_invoice.setObjectName(u"pushButton_load_invoice")
        self.pushButton_load_invoice.setGeometry(QRect(540, 30, 111, 40))
        self.plainTextEdit_invoice = QPlainTextEdit(self.tab_3)
        self.plainTextEdit_invoice.setObjectName(u"plainTextEdit_invoice")
        self.plainTextEdit_invoice.setGeometry(QRect(30, 160, 641, 391))
        sizePolicy.setHeightForWidth(self.plainTextEdit_invoice.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_invoice.setSizePolicy(sizePolicy)
        self.plainTextEdit_invoice.setFrameShape(QFrame.Shape.StyledPanel)
        self.plainTextEdit_invoice.setFrameShadow(QFrame.Shadow.Plain)
        self.label = QLabel(self.tab_3)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 30, 61, 40))
        self.pushButton_generate_invoice = QPushButton(self.tab_3)
        self.pushButton_generate_invoice.setObjectName(u"pushButton_generate_invoice")
        self.pushButton_generate_invoice.setGeometry(QRect(540, 90, 111, 40))
        self.label_generate_invoice = QLabel(self.tab_3)
        self.label_generate_invoice.setObjectName(u"label_generate_invoice")
        self.label_generate_invoice.setGeometry(QRect(150, 90, 351, 40))
        self.label_generate_invoice.setFrameShape(QFrame.Shape.Panel)
        self.label_generate_invoice.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_generate_invoice.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_2 = QLabel(self.tab_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(40, 90, 91, 41))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.label_naver_product_csv = QLabel(self.tab_2)
        self.label_naver_product_csv.setObjectName(u"label_naver_product_csv")
        self.label_naver_product_csv.setGeometry(QRect(410, 30, 151, 21))
        self.label_naver_product_csv.setFrameShape(QFrame.Shape.StyledPanel)
        self.checkBox = QCheckBox(self.tab_2)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(570, 30, 111, 20))
        self.label_naver_product_csv_2 = QLabel(self.tab_2)
        self.label_naver_product_csv_2.setObjectName(u"label_naver_product_csv_2")
        self.label_naver_product_csv_2.setGeometry(QRect(410, 60, 151, 21))
        self.label_naver_product_csv_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.lineEdit_idx_naver = QLineEdit(self.tab_2)
        self.lineEdit_idx_naver.setObjectName(u"lineEdit_idx_naver")
        self.lineEdit_idx_naver.setGeometry(QRect(110, 30, 71, 21))
        self.lineEdit_idx_coupang = QLineEdit(self.tab_2)
        self.lineEdit_idx_coupang.setObjectName(u"lineEdit_idx_coupang")
        self.lineEdit_idx_coupang.setGeometry(QRect(110, 60, 71, 21))
        self.label_3 = QLabel(self.tab_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 30, 71, 16))
        self.label_4 = QLabel(self.tab_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 60, 61, 16))
        self.lineEdit_idx_gmarket = QLineEdit(self.tab_2)
        self.lineEdit_idx_gmarket.setObjectName(u"lineEdit_idx_gmarket")
        self.lineEdit_idx_gmarket.setGeometry(QRect(110, 90, 71, 21))
        self.label_5 = QLabel(self.tab_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 90, 71, 16))
        self.label_database_name = QLabel(self.tab_2)
        self.label_database_name.setObjectName(u"label_database_name")
        self.label_database_name.setGeometry(QRect(150, 160, 351, 40))
        self.label_database_name.setFrameShape(QFrame.Shape.Panel)
        self.label_database_name.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_database_name.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.pushButton_load_database = QPushButton(self.tab_2)
        self.pushButton_load_database.setObjectName(u"pushButton_load_database")
        self.pushButton_load_database.setGeometry(QRect(540, 160, 111, 40))
        self.label_database = QLabel(self.tab_2)
        self.label_database.setObjectName(u"label_database")
        self.label_database.setGeometry(QRect(40, 160, 61, 40))
        self.tabWidget.addTab(self.tab_2, "")

        self.verticalLayout.addWidget(self.tabWidget)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 726, 33))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionOpenExcel)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Easy Fulfill - \uc8fc\ubb38 \ucc98\ub9ac \uc2dc\uc2a4\ud15c", None))
        MainWindow.setStyleSheet(QCoreApplication.translate("MainWindow", u"QMainWindow::separator {\n"
"    height: 1px;\n"
"    background: #CCCCCC;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}", None))
        self.actionOpenExcel.setText(QCoreApplication.translate("MainWindow", u"\uc5d1\uc140 \ud30c\uc77c \uc5f4\uae30(&O)", None))
#if QT_CONFIG(shortcut)
        self.actionOpenExcel.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"\uc885\ub8cc(&X)", None))
#if QT_CONFIG(shortcut)
        self.actionExit.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+F4", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"\ud504\ub85c\uadf8\ub7a8 \uc815\ubcf4(&A)", None))
        self.filePathLabel.setText(QCoreApplication.translate("MainWindow", u"\uc8fc\ubb38 \uc815\ubcf4\uac00 \uc5c6\uc2b5\ub2c8\ub2e4. ( Ctrl + O )", None))
        self.label_logo.setText(QCoreApplication.translate("MainWindow", u"image", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\uc8fc\ubb38\ucc98\ub9ac", None))
        self.label_invoice.setText(QCoreApplication.translate("MainWindow", u"\uc1a1\uc7a5 \uc815\ubcf4\uac00 \uc5c6\uc2b5\ub2c8\ub2e4.", None))
        self.pushButton_load_invoice.setText(QCoreApplication.translate("MainWindow", u"\ubd88\ub7ec\uc624\uae30", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\uc1a1\uc7a5 \uc815\ubcf4", None))
        self.pushButton_generate_invoice.setText(QCoreApplication.translate("MainWindow", u"\uc0dd\uc131", None))
        self.label_generate_invoice.setText(QCoreApplication.translate("MainWindow", u"\uc0dd\uc131 \ubc84\ud2bc\uc744 \ub204\ub974\uc138\uc694.", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\uc77c\uad04 \ubc1c\uc1a1 \ucd9c\ub825", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"\ubc1c\uc1a1\ucc98\ub9ac", None))
        self.label_naver_product_csv.setText(QCoreApplication.translate("MainWindow", u"\ub124\uc774\ubc84 \uc0c1\ud488 DB \ud30c\uc77c\uba85", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"\uc0c1\ud488 DB \uc0ac\uc6a9", None))
        self.label_naver_product_csv_2.setText(QCoreApplication.translate("MainWindow", u"\ucfe0\ud321 \uc0c1\ud488 DB \ud30c\uc77c\uba85", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\ub124\uc774\ubc84 \ubc88\ud638", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\ucfe0\ud321 \ubc88\ud638", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\uc9c0\ub9c8\ucf13 \ubc88\ud638", None))
        self.label_database_name.setText(QCoreApplication.translate("MainWindow", u"DataBase \uc815\ubcf4\uac00 \uc5c6\uc2b5\ub2c8\ub2e4.", None))
        self.pushButton_load_database.setText(QCoreApplication.translate("MainWindow", u"\ubd88\ub7ec\uc624\uae30", None))
        self.label_database.setText(QCoreApplication.translate("MainWindow", u"DB \uac31\uc2e0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\ud658\uacbd\uc124\uc815", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"\ud30c\uc77c(&F)", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"\ub3c4\uc6c0\ub9d0(&H)", None))
        self.statusbar.setStyleSheet(QCoreApplication.translate("MainWindow", u"QStatusBar {\n"
"    border-top: 1px solid #CCCCCC;\n"
"}", None))
    # retranslateUi

